//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuanVan
    {
        public int MaLV { get; set; }
        public Nullable<int> MaGV { get; set; }
        public string TenLV { get; set; }
        public string MoTa { get; set; }
        public string YeuCau { get; set; }
        public string ChucNang { get; set; }
        public Nullable<int> SoLuongSinhVien { get; set; }
        public string TinhTrang { get; set; }
        public string CongNghe { get; set; }
        public string TheLoai { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
    }
}
